version: '3.4'

services:
  backend:
    image: moltimate-backend
    container_name: moltimate-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        jarfile: target/moltimate-backend-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
